from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
import random
import string


def generate_invite_code():
    return "".join(random.choices(string.ascii_uppercase + string.digits, k=8))


class User(AbstractUser):
    """
    Custom user model with approval status.
    New self-registered users start as PENDING
    until approved by an estate manager.
    """
    STATUS_CHOICES = [
        ("pending",  "Pending Approval"),
        ("approved", "Approved"),
        ("rejected", "Rejected"),
    ]

    phone       = models.CharField(max_length=20, blank=True)
    avatar      = models.ImageField(upload_to="avatars/", null=True, blank=True)
    status      = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="pending",
        help_text="Pending = awaiting manager approval"
    )
    approved_by = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="approved_users"
    )
    approved_at = models.DateTimeField(null=True, blank=True)
    notes       = models.TextField(
        blank=True,
        help_text="Admin notes about this user"
    )

    def approve(self, approved_by_user):
        self.status      = "approved"
        self.approved_by = approved_by_user
        self.approved_at = timezone.now()
        self.is_active   = True
        self.save()

    def reject(self, rejected_by_user):
        self.status    = "rejected"
        self.is_active = False
        self.save()

    def __str__(self):
        return self.email or self.username


class EstateMembership(models.Model):
    """
    Links a User to an Estate with a specific role.
    """
    ROLES = [
        ("superadmin",     "Super Admin"),
        ("estate_admin",   "Estate Admin"),
        ("estate_manager", "Estate Manager"),
        ("security",       "Security Officer"),
        ("resident",       "Resident"),
        ("readonly",       "Read Only"),
    ]

    STATUS_CHOICES = [
        ("pending",  "Pending Approval"),
        ("approved", "Approved"),
        ("rejected", "Rejected"),
    ]

    user        = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="estate_memberships"
    )
    estate      = models.ForeignKey(
        "estates.Estate",
        on_delete=models.CASCADE,
        related_name="memberships"
    )
    role        = models.CharField(max_length=30, choices=ROLES, default="resident")
    status      = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending")
    is_active   = models.BooleanField(default=False)   # False until approved
    joined_at   = models.DateTimeField(auto_now_add=True)
    approved_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="approved_memberships"
    )
    approved_at = models.DateTimeField(null=True, blank=True)
    unit_number = models.CharField(
        max_length=20,
        blank=True,
        help_text="Unit number provided during registration (unverified)"
    )
    notes       = models.TextField(blank=True)

    class Meta:
        unique_together = ["user", "estate"]

    def approve(self, approved_by_user):
        self.status      = "approved"
        self.is_active   = True
        self.approved_by = approved_by_user
        self.approved_at = timezone.now()
        self.save()
        # Also activate the user account itself
        if not self.user.is_active:
            self.user.is_active = True
            self.user.status    = "approved"
            self.user.save()

    def reject(self, rejected_by_user):
        self.status    = "rejected"
        self.is_active = False
        self.save()

    def __str__(self):
        return f"{self.user.username} — {self.estate.name} ({self.role})"


class EstateInvite(models.Model):
    """
    Invite links generated by estate managers.
    Anyone who registers with a valid invite code is
    automatically approved and assigned to the estate.
    """
    estate      = models.ForeignKey(
        "estates.Estate",
        on_delete=models.CASCADE,
        related_name="invites"
    )
    created_by  = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="created_invites"
    )
    code        = models.CharField(
        max_length=20,
        unique=True,
        default=generate_invite_code
    )
    role        = models.CharField(
        max_length=30,
        choices=EstateMembership.ROLES,
        default="resident",
        help_text="Role assigned to anyone who registers with this link"
    )
    max_uses    = models.PositiveIntegerField(
        default=1,
        help_text="How many times this invite can be used. 0 = unlimited"
    )
    times_used  = models.PositiveIntegerField(default=0)
    expires_at  = models.DateTimeField(
        null=True, blank=True,
        help_text="Leave blank for no expiry"
    )
    is_active   = models.BooleanField(default=True)
    created_at  = models.DateTimeField(auto_now_add=True)

    @property
    def is_valid(self):
        if not self.is_active:
            return False
        if self.expires_at and timezone.now() > self.expires_at:
            return False
        if self.max_uses > 0 and self.times_used >= self.max_uses:
            return False
        return True

    def use(self):
        self.times_used += 1
        self.save(update_fields=["times_used"])

    def __str__(self):
        return f"Invite to {self.estate.name} [{self.code}] — {self.role}"