# Generated by Django 5.2.12 on 2026-03-08 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('maintenance', 'Maintenance'), ('financial', 'Financial')], default='general', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('attachment', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
