# Generated by Django 5.2.12 on 2026-03-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='config',
        ),
        migrations.AddField(
            model_name='estate',
            name='currency',
            field=models.CharField(default='ZAR', help_text='Currency code e.g. ZAR, USD', max_length=10),
        ),
        migrations.AddField(
            model_name='estate',
            name='late_penalty_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Penalty percentage applied to overdue accounts', max_digits=5),
        ),
        migrations.AddField(
            model_name='estate',
            name='levy_due_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of the month levies are due (1-28)'),
        ),
        migrations.AddField(
            model_name='estate',
            name='monthly_levy_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly levy amount charged to each unit (ZAR)', max_digits=10),
        ),
    ]
