# Generated by Django 5.2.12 on 2026-03-08 13:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estates', '0001_initial'),
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevyBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_month', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('outstanding', 'Outstanding'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='outstanding', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='estates.estate')),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levy_billings', to='residents.resident')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levy_billings', to='residents.unit')),
            ],
            options={
                'ordering': ['-billing_month'],
                'unique_together': {('unit', 'billing_month')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('eft', 'EFT / Bank Transfer'), ('cash', 'Cash'), ('debit_order', 'Debit Order'), ('card', 'Card')], default='eft', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('proof_document', models.CharField(blank=True, max_length=500)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='estates.estate')),
                ('levy_billing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='levies.levybilling')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='residents.resident')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
