# Generated by Django 5.2.12 on 2026-03-08 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_remove_estate_config_estate_currency_and_more'),
        ('levies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevyRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. '2 Bedroom Apartment' or 'Large House'", max_length=100)),
                ('unit_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('townhouse', 'Townhouse'), ('penthouse', 'Penthouse'), ('studio', 'Studio'), ('commercial', 'Commercial'), ('other', 'Other')], help_text='Leave blank to apply to all unit types', max_length=20)),
                ('min_size_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum floor size in m² (leave blank for no minimum)', max_digits=8, null=True)),
                ('max_size_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum floor size in m² (leave blank for no maximum)', max_digits=8, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, help_text='Number of bedrooms (leave blank to apply to all)', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monthly levy amount in ZAR', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(help_text='Date this rate comes into effect')),
                ('effective_to', models.DateField(blank=True, help_text='Leave blank if this rate has no end date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this rate')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='estates.estate')),
            ],
            options={
                'ordering': ['unit_type', 'min_size_sqm', 'bedrooms'],
            },
        ),
        migrations.AddField(
            model_name='levybilling',
            name='levy_rate',
            field=models.ForeignKey(blank=True, help_text='The rate that was applied for this billing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='levies.levyrate'),
        ),
    ]
