# Generated by Django 5.2.12 on 2026-03-08 13:34

import apps.visitors.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estates', '0001_initial'),
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPreRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_id_number', models.CharField(blank=True, max_length=20)),
                ('visitor_phone', models.CharField(blank=True, max_length=20)),
                ('expected_arrival', models.DateTimeField()),
                ('expected_departure', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('social', 'Social Visit'), ('delivery', 'Delivery'), ('contractor', 'Contractor'), ('service', 'Service Provider')], default='social', max_length=50)),
                ('access_code', models.CharField(default=apps.visitors.models.generate_access_code, max_length=10, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='estates.estate')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_invitations', to='residents.resident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_id_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_registration', models.CharField(blank=True, max_length=20)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='estates.estate')),
                ('host_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residents.resident')),
                ('security_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pre_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_logs', to='visitors.visitorpreregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
