# Generated by Django 5.2.12 on 2026-03-08 14:53

import apps.authentication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('estates', '0002_remove_estate_config_estate_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatemembership',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatemembership',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estatemembership',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estatemembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='estatemembership',
            name='unit_number',
            field=models.CharField(blank=True, help_text='Unit number provided during registration (unverified)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes about this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Pending = awaiting manager approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='estatemembership',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EstateInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.authentication.models.generate_invite_code, max_length=20, unique=True)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('estate_admin', 'Estate Admin'), ('estate_manager', 'Estate Manager'), ('security', 'Security Officer'), ('resident', 'Resident'), ('readonly', 'Read Only')], default='resident', help_text='Role assigned to anyone who registers with this link', max_length=30)),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='How many times this invite can be used. 0 = unlimited')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='estates.estate')),
            ],
        ),
    ]
